#!/bin/sh
#
# PROVIDE: esphome
# REQUIRE: LOGIN
# KEYWORD: shutdown
#

# shellcheck disable=SC1091,2034
name=esphome
rcvar=${name}_enable

. /etc/rc.subr && load_rc_config ${name}

: "${esphome_enable:='NO'}"
: "${esphome_user:='esphome'}"
: "${esphome_group:='esphome'}"
: "${esphome_config_dir:='/var/db/esphome'}"
: "${esphome_venv:='/usr/local/srv/esphome'}"

command='/usr/sbin/daemon'

logfile="/var/log/${name}_daemon.log"
pidfile="/var/run/${name}_daemon.pid"
pidfile_child="/var/run/${name}.pid"

start_precmd="${name}_precmd"
esphome_precmd() {
  HOME="$(getent passwd "${esphome_user}" | cut -d: -f6)"
  PATH="${esphome_venv}/bin:${PATH}"
  install -g ${esphome_group} -o ${esphome_user} -- /dev/null "${logfile}"
  install -g ${esphome_group} -o ${esphome_user} -- /dev/null "${pidfile}"
  install -g ${esphome_group} -o ${esphome_user} -- /dev/null "${pidfile_child}"
  rc_flags="-f -o ${logfile} -P ${pidfile} -p ${pidfile_child} esphome dashboard ${esphome_config_dir}"
}

start_postcmd="${name}_poststart"
esphome_poststart() {
  sleep 1
  run_rc_command status
}

stop_postcmd="${name}_postcmd"
esphome_postcmd() {
  rm -f -- "${pidfile}"
  rm -f -- "${pidfile_child}"
}

umask "${esphome_umask:-022}"
run_rc_command "${1}"
